version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "04:00"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: "@babel/runtime"
    versions:
    - 7.13.17
    - 7.13.8
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.13.15
    - 7.13.8
  - dependency-name: rollup
    versions:
    - 2.38.2
    - 2.40.0
  - dependency-name: "@babel/plugin-transform-runtime"
    versions:
    - 7.13.8
  - dependency-name: svelte
    versions:
    - 3.32.1
  - dependency-name: sapper
    versions:
    - 0.29.0
