# TODO: revisit once https://github.com/dependabot/dependabot-core/issues/1297 is resolved
name: dependabot integration

on:
  push:
    branches:
      # TODO for testing only, remove first entry later
      - 'chore/*'
      - 'dependabot/npm_and_yarn/**'
jobs:
  fix-yarn-berry-integration:
    runs-on: ubuntu-latest

    steps:
      - uses: hmarr/debug-action@master

      - uses: actions/checkout@v2
        with:
          persist-credentials: true

      - name: 'Install packages'
        run: |
          yarn install
        

      - name: 'Autofix yarn for dependabot'
        run: |
          git add -A
          git status
          git diff-index --quiet HEAD || (git commit  --message 'yarn autofix' && git push -u origin HEAD:{{ github.ref }})
        # Pushes from actions can't trigger actions.
        # The below statement isn't needed.
        # if: {{ github.action === "dependabot-preview" }}